# Generated by Django 6.1.2 on 2026-10-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('trial_ends_at__gt', models.F('trial_starts_at'))), name='tenant_trial_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['super_admin', 'admin', 'super_viewer']), ('tenant__isnull', True)), models.Q(('role__in', ['tenant_admin', 'tenant_user']), ('tenant__isnull', False)), _connector='OR'), name='user_role_tenant_membership_valid'),
        ),
    ]
