# Generated by Django 6.1.2 on 2026-10-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
