# Generated by Django 6.1.2 on 2026-10-09 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='brand_color',
            field=models.CharField(default='#09090b', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a 6-digit hex color.')]),
        ),
    ]
