# Generated by Django 6.1.2 on 2026-10-09 12:13

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='LessonAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=core.models.lesson_asset_upload_to)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('mime_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.lesson')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'video')), fields=('lesson',), name='one_video_asset_per_lesson')],
            },
        ),
    ]
