# Generated by Django 6.1.2 on 2026-10-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lesson_description_lessonasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('subscribed', 'Subscribed')], default='trial', max_length=20),
        ),
    ]
