# Generated by Django 6.1.2 on 2026-10-09 12:37

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, upload_to=core.models.tenant_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to=core.models.user_avatar_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
    ]
