# Generated by Django 6.1.2 on 2026-10-09 14:18

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tenant_address_tenant_contact_phone_tenant_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
    ]
