# Generated by Django 6.1.2 on 2026-10-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lessonasset',
            name='one_video_asset_per_lesson',
        ),
    ]
