# Generated by Django 6.1.2 on 2026-10-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_lessonasset_one_video_asset_per_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonasset',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
